on:
  workflow_dispatch:
    inputs:
      service_name:
        description: 'K8s Deployment name to patch (e.g., service-a)'
        required: true
      namespace:
        description: 'K8s Namespace (e.g., dev)'
        required: true
      image_tag:
        description: 'New image tag (e.g., sha256:abcd1234 or latest)'
        required: true
