name: Deploy to Kubernetes

on:
  workflow_dispatch:
    inputs:
      image_sha:
        description: 'Docker Image SHA'
        required: true
        default: 'latest'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set image tag
        run: echo "IMAGE_TAG=${{ github.event.inputs.image_sha }}" >> $GITHUB_ENV

      - name: Echo the SHA
        run: echo "Image SHA provided:${{ github.event.inputs.image_sha }}"
