on:
  workflow_dispatch:
    inputs:
      namespace:
        description: 'Namespace'
        required: true
        type: choice
        options:
          - back
          - front
          - keycloak

      service_name:
        description: 'Service (Deployment Name)'
        required: true
        type: choice
        options:
          - front
          - back
          - keycloak

      image_tag:
        description: 'New Image Tag or SHA'
        required: true
